[package]
name = "hearth"
version = "0.0.6"
edition = "2018"

[dependencies]
rand = "0.7"
futures = "0.1"
log = "0.4"
env_logger = "0.6"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
toml = "0.5"
actix = "0.8"
actix-rt = "0.2"
actix-web = "1.0"
actix-files = "0.1"
actix-web-actors = "1.0"
ssh2 = "0.3"
derive_more = "0.15"

[profile.release]
lto = "thin"
opt-level = 3

[workspace]
